# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  deployment-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
          name: build
          command: |
            npm i tsc && npm run tsc
      - aws-elastic-beanstalk/setup
      - run: cd dist && eb-deploy
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/run:
            yarn-run: yarn global add tsc
      - node/test:
          requires:
            - node/run
      - deployment-job:
          requires:
            - node/test
